language: ruby
sudo: false
rvm:
- 2.1
- 2.2.2
- 2.3.3
- ruby-head
cache: bundler
before_script:
- bundle exec rake db:migrate
env:
  global:
    secure: a+K4odT4GG5TVJ/vgK4JRcgV1ZaT8uLNNshf0h0ZjOsJQEvc60NF7i4C8epZatnx66YhKHzFaI3T/hvmVVbtefanBCnPfCH1NJQWFpmaeya8M7GBPWmQgXVpgqWR3tVuOZNzTQDEAdAg04JMYdGs1hDY9P+RIHHBbj7yeVgQZcI=
gemfile:
- gemfiles/Gemfile-rails-4.0.x
- gemfiles/Gemfile-rails-4.1.x
- gemfiles/Gemfile-rails-4.2.x
- gemfiles/Gemfile-rails-5.0.x
- gemfiles/Gemfile-rails-edge
matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/Gemfile-rails-5.0.x
    - rvm: 2.1
      gemfile: gemfiles/Gemfile-rails-edge
  allow_failures:
      - rvm: ruby-head
      - gemfile: gemfiles/Gemfile-rails-edge
