language: ruby
sudo: false
rvm:
- 2.3.8
- 2.4.6
- 2.5.5
- 2.6.3
- ruby-head
cache: bundler
before_install:
- rvm use @global
- gem update --system # Need for Ruby 2.5.0. https://github.com/travis-ci/travis-ci/issues/8978
- gem uninstall bundler -x
- gem install --force bundler -v 1.17.3
before_script:
- bundle exec rake db:migrate
env:
  global:
    secure: a+K4odT4GG5TVJ/vgK4JRcgV1ZaT8uLNNshf0h0ZjOsJQEvc60NF7i4C8epZatnx66YhKHzFaI3T/hvmVVbtefanBCnPfCH1NJQWFpmaeya8M7GBPWmQgXVpgqWR3tVuOZNzTQDEAdAg04JMYdGs1hDY9P+RIHHBbj7yeVgQZcI=
gemfile:
- gemfiles/Gemfile-rails-5.1.x
- gemfiles/Gemfile-rails-5.2.x
- gemfiles/Gemfile-rails-6.0.x
- gemfiles/Gemfile-rails-edge
matrix:
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile-rails-6.0.x
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile-rails-5.2.x
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile-rails-5.1.x
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile-rails-edge
    - rvm: 2.4.6
      gemfile: gemfiles/Gemfile-rails-6.0.x
  allow_failures:
      - rvm: ruby-head
      - gemfile: gemfiles/Gemfile-rails-edge
